# Generated by Django 5.2.11 on 2026-03-02 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='customer_id',
        ),
    ]
