# Generated by Django 5.2.11 on 2026-03-03 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_subcategory_name', models.CharField(max_length=50)),
                ('sub_subcategory_description', models.CharField(max_length=200)),
                ('sub_subcategory_image', models.ImageField(blank=True, null=True, upload_to='sub_subcategory/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_subcategories', to='core.subcategory')),
            ],
        ),
    ]
