# Generated by Django 5.2.11 on 2026-03-13 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_wishlist_added_at_remove_wishlist_id_and_more'),
        ('seller', '0002_alter_productimage_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='seller.productvariant'),
        ),
    ]
